### ISSUE TITLE
OnSMSReceived event don't work for me 

### ISSUE THREAD

**Issue by christopharus** [pravinkumarputta/nativescript-sms-receiver#1]
I am trying to use the  script to automatically take incoming sms but the event OnSMSReceived never give me the alert I want . I use it on Android R .The timeout event works correctly and the OnSMSReceiverStarted

**Comment by pravinkumarputta** [comment]
@christopharus thanks for reporting an issue, I will update soon.

**Comment by pravinkumarputta** [comment]
@christopharus I have checked it on the Android R emulator, it's working perfectly. 
You can see a demo on below link:
[Click here for demo](https://drive.google.com/open?id=1u46eIMSIMoOX9H9pFXMWdhlU8tkGlm0_)

I think your implementation has some mistakes. Please check once and let me know is it working.

**Comment by christopharus** [comment]
Hi  @Pravinkumar  .
Could I have a look on your code ?
Or have a look on my code https://drive.google.com/file/d/1qRCr3Lw1a1e9LhoD60s8nKMOsSG2nnpL/view?usp=sharing

https://drive.google.com/open?id=1zUwvy4n15ekp-FKSG6cGjyEibPNlSTNC

I am going to try it again  and make you know what's happen  ?

**Comment by pravinkumarputta** [comment]
@christopharus 
You can check code by cloning this project and run a demo.

**Comment by pravinkumarputta** [comment]
did it worked???

**Comment by pravinkumarputta** [comment]
> @christopharus
> You can check code by cloning this project and run a demo.

did it worked??

**Comment by christopharus** [comment]
I am still trying to run it .It seems that I need to migrate the project but I'm still getting an error .May be I'll sharing you the log

**Comment by pravinkumarputta** [comment]
@christopharus 
Try to replace below line demo/package.json file,
"nativescript-sms-receiver": "file:///d:\\MyPlugins\\github\\nativescript\\nativescript-sms-receiver\\src",

With

"nativescript-sms-receiver": "file:../src",


And migrate it using tns migrate, then it will work.

**Comment by christopharus** [comment]
I am now getting a problem with the emulator .I don't understant why the emulator and android build tools works for my other project and don't work for this one

**Comment by christopharus** [comment]
Since the last 2 days I am trying to run the project without success 
![Screenshot (37)](https://user-images.githubusercontent.com/47279703/77625466-9ef1df00-6f11-11ea-825c-ed865b223b96.png)

I can't run : _tns run android_ neither _tns update_

**Comment by pravinkumarputta** [comment]
@christopharus 
Please check your nativescript version.

**Comment by christopharus** [comment]
This is the version I get 
![Screenshot (39)](https://user-images.githubusercontent.com/47279703/77777828-1ca31100-701e-11ea-8ae3-503723b87222.png)

**Comment by pravinkumarputta** [comment]
@christopharus 
Please download below zip. I'm sharing my migrated demo zip with you. Try this once and let me know is it working or not.
[Click here to download](https://drive.google.com/open?id=1EMDH5AZHrYgkMRDclxd3TNwpzS0kanoi)

**Comment by christopharus** [comment]
This is what I get for **tns update and tns migrate**
![Screenshot (48)](https://user-images.githubusercontent.com/47279703/77784238-36e1ec80-7028-11ea-9ccf-e56b026e2ed8.png)
This is what I get for tns run android :
![Screenshot (44)](https://user-images.githubusercontent.com/47279703/77784331-55e07e80-7028-11ea-97f4-3c7d04b67a8f.png)
![Screenshot (45)](https://user-images.githubusercontent.com/47279703/77784383-6db80280-7028-11ea-8f31-60ceffc649ea.png)

**Comment by pravinkumarputta** [comment]
@christopharus 
Sorry for the inconvenience. This plugin is not working for latest nativescript version. I'll have to update the plugin to support the latest version.

**Comment by christopharus** [comment]
okk thank you

**Comment by pravinkumarputta** [comment]
@christopharus 
Please check with the new plugin update. I have tried with the demo app having nativescript version 6.3.3.
[Click to Download Demo Source](https://drive.google.com/open?id=1mLCQjGjMsipCvhNzJxUkrc4D0fE4r1TY)

**Comment by christopharus** [comment]
**The first tns run give this :**

![Screenshot (53)](https://user-images.githubusercontent.com/47279703/77833501-d7f5a380-710b-11ea-8391-9f5aa5e73837.png)
![Screenshot (54)](https://user-images.githubusercontent.com/47279703/77833538-29059780-710c-11ea-94db-b9e639a03149.png)

**The second one give this :**
![Screenshot (55)](https://user-images.githubusercontent.com/47279703/77833575-708c2380-710c-11ea-8bac-be3e70a2fe62.png)

**Comment by pravinkumarputta** [comment]
@christopharus 
Copy code into other drive except C drive and try again. I think there is an issue with permissions.

**Comment by christopharus** [comment]
**this is  what i get :**
![Screenshot (57)](https://user-images.githubusercontent.com/47279703/77834493-12167380-7113-11ea-9b38-ffb898cd1a3e.png)

**Comment by pravinkumarputta** [comment]
@christopharus 
You are near to the solution. Please delete node modules and re-install, then try again.
Still, if you face any error first google it otherwise ping me. See below it may help.
[Click here](https://github.com/felixrieseberg/npm-windows-upgrade/issues/113)

**Comment by christopharus** [comment]
It's work finally .Thank you very much
