### ISSUE TITLE
Works on iOS?

### ISSUE THREAD

**Issue by luiguild** [pravinkumarputta/nativescript-sms-receiver#2]

**Comment by pravinkumarputta** [comment]
It's only for android.

**Comment by arturikoX** [comment]
Hi,
Love the plugin, thanks !
Do you think you will support IOS in the close future ?

**Comment by pravinkumarputta** [comment]
Hi,

In iOS sms detection is not possible but there is an alternative solution
for this without any plugin. Please check below link.

https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

Hopefully it’ll help you.
